name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check secrets
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          test -n "$DOCKER_USER" || (echo "DOCKERHUB_USERNAME is missing" && exit 1)
          test -n "$DOCKER_TOKEN" || (echo "DOCKERHUB_TOKEN is missing" && exit 1)
          test -n "$VAULT_ADDR" || (echo "VAULT_ADDR is missing" && exit 1)
          test -n "$VAULT_TOKEN" || (echo "VAULT_TOKEN is missing" && exit 1)

          echo "Secrets are configured"

      - name: Check Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          curl -fsS \
            -H "X-Vault-Token: $VAULT_TOKEN" \
            "$VAULT_ADDR/v1/auth/token/lookup-self"

          echo
          echo "Vault connection OK"

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/Dockerfile
          push: true
